version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.7.0
    environment:
      - network.host= 127.0.0.1
      - http.port=9200
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - '9200:9200'
      - '9300:9300'
